const visitors=[
 {name:'ИГОРЬ, 34',mood:'НЕРВНИЧАЕТ',tag:'«БЫСТРО И БЕЗ ВОПРОСОВ»',skin:'#c59570',coat:'#384e47',hair:'#332b27',line:'Мне бы чего-нибудь… ну, чтобы всю ночь не спать. И посильнее. Рецепта нет, но я постоянный.',choices:[['Продать рецептурный стимулятор','₽₽ · высокий риск',{money:2400,trust:-14,risk:35},'Касса звякнула, но камера над входом всё записала. Профессиональная удача стала короче.'],['Предложить безопасный безрецептурный вариант','₽ · разумно',{money:430,trust:8,risk:0},'Игорь ворчит, но слушает про дозировку. Сегодня вы не стали частью его проблемы.'],['Отказать и попросить покинуть аптеку','без продажи',{money:0,trust:-3,risk:-2},'Формально верно, но разговор оборван слишком резко. Он хлопает дверью.']]},
 {name:'ЗИНАИДА, 72',mood:'ПЛОХО СЛЫШИТ',tag:'«КАК В РЕКЛАМЕ»',skin:'#d7aa8d',coat:'#7f655b',hair:'#d9d4c9',line:'Милок, дай те таблетки, которые по телевизору от сердца. Название синее… или коробочка синяя?',choices:[['Продать самый популярный сердечный препарат','₽₽ · наугад',{money:1150,trust:-8,risk:24},'Вы угадали с цветом коробки, но не с назначением. Опасная лотерея.'],['Уточнить симптомы и вызвать скорую','время · безопасно',{money:0,trust:18,risk:-4},'Боль отдаёт в левую руку. Через семь минут Зинаида уже под наблюдением врачей.'],['Показать витрину: пусть узнает сама','₽ · сомнительно',{money:620,trust:-4,risk:12},'Она выбирает знакомую упаковку. Вы всё ещё не знаете, кому она была назначена.']]},
 {name:'АНТОН, 9',mood:'ГОВОРИТ ШЁПОТОМ',tag:'«МАМЕ НЕ ГОВОРИ»',skin:'#d9a27d',coat:'#d68c3f',hair:'#6f4932',line:'У меня живот болит. Мама в машине. Можно что-нибудь вкусное, которое лечит?',choices:[['Дать детское обезболивающее','₽ · быстро',{money:280,trust:-4,risk:16},'Боль может быть симптомом аппендицита. Маскировать её без взрослого — плохая ставка.'],['Позвать маму и задать вопросы','диалог',{money:180,trust:14,risk:-2},'Мама заходит. После нескольких вопросов вы советуете не аптеку, а осмотр врача.'],['Продать мятные пастилки','маленькая хитрость',{money:90,trust:3,risk:3},'Вкусно — да. Лечение — нет. Зато вы выигрываете минуту, чтобы позвать взрослого.']]},
 {name:'МАРИНА, 29',mood:'БЕРЕМЕННА, 8 МЕСЯЦ',tag:'«ТОЛЬКО НАТУРАЛЬНОЕ»',skin:'#c98e70',coat:'#7f9872',hair:'#5a392d',line:'Отёки замучили. Дайте что-нибудь натуральное мочегонное — травки же точно безопасны?',choices:[['Продать травяной сбор','₽ · натурально',{money:360,trust:-6,risk:21},'«Натуральное» не значит безопасное, особенно на позднем сроке.'],['Измерить давление и направить к врачу','внимательно',{money:0,trust:17,risk:-5},'Давление повышено. Марина звонит врачу — вы вовремя заметили тревожный признак.'],['Посоветовать просто меньше пить','бесплатно · неверно',{money:0,trust:-9,risk:13},'Универсальный совет оказался неуместным и потенциально опасным.']]},
 {name:'ГЕННАДИЙ, 51',mood:'ПАХНЕТ АЛКОГОЛЕМ',tag:'«ДРУГ ПОСОВЕТОВАЛ»',skin:'#bd765b',coat:'#48546b',hair:'#382f2b',line:'Башка раскалывается. Дай сильное обезболивающее. Да я всего пару рюмок, нормально всё.',choices:[['Продать что просит','₽₽ · риск сочетания',{money:740,trust:-7,risk:23},'Алкоголь и лекарство — сочетание с неприятными последствиями.'],['Уточнить, что и сколько выпил','разговор',{money:190,trust:12,risk:-2},'«Пара» превращается в бутылку. Вы предлагаете воду, безопасный вариант и наблюдение близких.'],['Продать сорбент и минералку','₽ · компромисс',{money:310,trust:5,risk:4},'Не волшебство, но вреда меньше. Геннадий обещает прочитать инструкцию — когда протрезвеет.']]},
 {name:'ЭЛЬВИРА, 42',mood:'СНИМАЕТ НА ТЕЛЕФОН',tag:'«Я ЗНАЮ СВОИ ПРАВА»',skin:'#af795f',coat:'#302f3d',hair:'#141519',line:'Почему вы не продаёте антибиотик без рецепта? Назовите закон. Я веду прямой эфир.',choices:[['Продать, чтобы избежать скандала','₽₽ · капитуляция',{money:980,trust:-15,risk:32},'Эфир закончился, а нарушение осталось. Зрители получили плохой урок.'],['Спокойно объяснить правила и предложить врача','профессионально',{money:0,trust:16,risk:-3},'Чат эфира неожиданно встаёт на вашу сторону. Эльвира уходит раздражённой, но с адресом дежурной клиники.'],['Начать снимать её в ответ','конфликт',{money:0,trust:-12,risk:9},'Теперь в эфире двое взрослых с телефонами и ни одного фармацевта.']]}
];
const reactions=[
 ['Вот это сервис. Пять звёзд поставлю… если вспомню, как меня зовут.','Кофеин? Ты серьёзно? Я сюда не капучино пить пришёл.','Да иди ты на три буквы со своей лицензией. Напишу, что у вас бахилы несвежие.'],
 ['Вот! Точно такая синенькая была. Или от унитаза реклама… Ну, дома разберусь.','Ой, милок, спасибо. А скидка пенсионная на скорую распространяется?','Зрение минус семь, зато выбор предоставили. Демократия!'],
 ['А оно точно вкусное? Если горькое, я напишу на вас маме.','Ну всё, операция провалена. Отменяйте эвакуацию и удаляйте переписку.','Это конфета за девяносто рублей. Я ребёнок, а не инвестор.'],
 ['Вот видите — природа всё придумала. Инструкцию читать не буду, там одна химия.','Спасибо. Я думала, вы сейчас опять ромашку предложите и пожелаете не нервничать.','Гениально. Может, ещё меньше дышать, чтобы отёки не надувались?'],
 ['Вот профессионал! Сразу видно — человек понимает взаимодействие культур и препаратов.','Воды? Я просил медицинскую помощь, а не экскурсию к кулеру.','Минералка — база. Сорбент — стратегия. Я всегда говорил: здоровье должно быть системным.'],
 ['Друзья, фиксируем победу гражданского общества! Промокода не будет — они не предложили.','Я вообще-то пришла за конфликтом… Но ладно. Ссылку на клинику киньте в комментарии.','Так, друзья, неожиданный поворот: у фармацевта тоже есть контент-план.']
];
let turn=0,stats={money:0,trust:50,risk:0};
const $=id=>document.getElementById(id),customer=$('customer'),speech=$('speech');
let soundOn=true,audio;
function tone(notes,type='sine'){
 if(!soundOn)return;
 audio??=new (window.AudioContext||window.webkitAudioContext)();
 notes.forEach(([freq,start,duration,volume=.08])=>{const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime+start;o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(volume,t+.01);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g).connect(audio.destination);o.start(t);o.stop(t+duration)});
}
const sounds={click:()=>tone([[420,0,.06,.04]],'square'),door:()=>tone([[660,0,.16],[880,.1,.28]],'sine'),cash:()=>tone([[880,0,.08],[1175,.07,.1],[1568,.15,.22]],'triangle'),risk:()=>tone([[170,0,.18],[125,.12,.3]],'sawtooth'),good:()=>tone([[523,0,.12],[659,.1,.12],[784,.2,.24]],'sine')};
function speak(){if(!soundOn)return;speech.src=`assets/voices/${turn+1}.wav`;speech.play().catch(()=>{})}
function startGame(){
 speech.src='assets/voices/1.wav';speech.volume=0;speech.play().then(()=>{speech.pause();speech.currentTime=0;speech.volume=1}).catch(()=>{speech.volume=1});
 sounds.click();document.body.classList.remove('not-started');$('intro').hidden=true;customer.className='customer exit';
 setTimeout(()=>{render();sounds.door();speak()},1000);
}
function render(){const v=visitors[turn];$('progress').textContent=`${String(turn+1).padStart(2,'0')} / ${String(visitors.length).padStart(2,'0')}`;$('progressBar').style.width=`${(turn+1)/visitors.length*100}%`;$('caseTag').textContent=`ПОСЕТИТЕЛЬ #${String(turn+1).padStart(2,'0')}`;$('name').textContent=v.name;$('mood').textContent=v.mood;$('line').textContent=v.line;$('badge').textContent=v.tag;customer.style.setProperty('--skin',v.skin);customer.style.setProperty('--coat',v.coat);customer.querySelector('.hair').style.background=v.hair;$('choices').innerHTML=v.choices.map((c,i)=>`<button class="choice" data-i="${i}"><b>${i+1}</b><span>${c[0]}</span><small>${c[1]}</small></button>`).join('');$('queue').innerHTML='<i></i>'.repeat(visitors.length-turn-1);customer.className='customer enter'}
function choose(i){const c=visitors[turn].choices[i],d=c[2];d.risk>=15?sounds.risk():d.trust>=8?sounds.good():d.money?sounds.cash():sounds.click();stats.money+=d.money;stats.trust=Math.max(0,Math.min(100,stats.trust+d.trust));stats.risk=Math.max(0,stats.risk+d.risk);$('money').textContent=`₽ ${stats.money.toLocaleString('ru')}`;$('trust').textContent=stats.trust;$('risk').textContent=stats.risk;$('resultText').innerHTML=`<strong>«${reactions[turn][i]}»</strong><small>${c[3]}</small>`;$('result').hidden=false;$('choices').querySelectorAll('button').forEach(b=>b.disabled=true);customer.classList.add('exit')}
function finish(){let title,text;if(stats.risk>=70){title='ЛИЦЕНЗИЯ ПОД УГРОЗОЙ';text='Касса довольна, но проверка уже близко. Вы слишком часто выбирали удобство вместо безопасности.'}else if(stats.trust>=85&&stats.risk<30){title='АПТЕКА, КОТОРОЙ ВЕРЯТ';text='Вы не всегда продавали лекарство — иногда внимательность была лучшим назначением. Район это запомнил.'}else{title='ОБЫЧНАЯ НОЧЬ';text='Вы удержали аптеку на плаву. Не идеально, но утро встретили с открытой дверью и работающей лицензией.'}$('endingTitle').textContent=title;$('endingText').textContent=`Касса: ₽ ${stats.money.toLocaleString('ru')} · доверие: ${stats.trust} · риск: ${stats.risk}. ${text}`;$('ending').hidden=false}
$('start').onclick=startGame;$('choices').addEventListener('click',e=>{const b=e.target.closest('button');if(b){speech.pause();choose(+b.dataset.i)}});$('voice').onclick=speak;$('next').onclick=()=>{$('result').hidden=true;if(++turn===visitors.length)finish();else{render();sounds.door();setTimeout(speak,250)}};$('restart').onclick=()=>{turn=0;stats={money:0,trust:50,risk:0};$('money').textContent='₽ 0';$('trust').textContent=50;$('risk').textContent=0;$('ending').hidden=true;render();sounds.door();setTimeout(speak,250)};$('sound').onclick=e=>{soundOn=!soundOn;e.currentTarget.textContent=`ЗВУК: ${soundOn?'ВКЛ':'ВЫКЛ'}`;if(soundOn)sounds.good();else speech.pause()};
render();
